"""
Run once to create the SQLite database schema.
Usage: python migrations/init_db.py
"""
import sqlite3
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from dotenv import load_dotenv

load_dotenv()

DB_PATH = os.getenv("DATABASE_URL", "sqlite:///./data/digital_twin.db")
# Strip sqlite:/// prefix
DB_FILE = DB_PATH.replace("sqlite:///", "")
os.makedirs(os.path.dirname(DB_FILE) if os.path.dirname(DB_FILE) else ".", exist_ok=True)

SCHEMA = """
CREATE TABLE IF NOT EXISTS entries (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    pillar      TEXT NOT NULL CHECK(pillar IN ('wealth','health','relationships','general')),
    raw_text    TEXT NOT NULL,
    summary     TEXT,
    entities    TEXT,          -- JSON array: people, companies, amounts, dates
    sentiment   TEXT,          -- positive / neutral / negative
    importance  INTEGER DEFAULT 5, -- 1-10, set by triage
    source      TEXT DEFAULT 'text', -- text | voice
    chroma_id   TEXT           -- reference to ChromaDB document
);

CREATE INDEX IF NOT EXISTS idx_entries_pillar    ON entries(pillar);
CREATE INDEX IF NOT EXISTS idx_entries_created   ON entries(created_at);
CREATE INDEX IF NOT EXISTS idx_entries_importance ON entries(importance);

CREATE TABLE IF NOT EXISTS daily_briefs (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    brief_text TEXT NOT NULL
);

-- Synthetic memories generated by the Muse background agent
CREATE TABLE IF NOT EXISTS synthetic_memories (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    insight    TEXT NOT NULL,
    pillars    TEXT,  -- comma-separated: wealth,health
    importance INTEGER DEFAULT 7,
    chroma_id  TEXT
);
"""

def main():
    conn = sqlite3.connect(DB_FILE)
    conn.executescript(SCHEMA)
    conn.commit()
    conn.close()
    print(f"✅ Database initialised at: {DB_FILE}")

if __name__ == "__main__":
    main()
